= Configuration file

The configuration file `vt-map-service.yaml` is a regular YAML file. 

== Template
Here is a template for the configuration:

```
storage:
    type: sqlite
    database: ./data/vt-map-service.db
geocoder:
    ### BKG Geocoder
    api: bkg
    api_key:
    suggest_params:        
        count: 5
        bbox: 6,51,12,54
    search_params: 
        bbox: 6,51,12,54
    
    ### Openrouteservice
    #api: ors
    #api_key:    
    #suggest_params:            
    #    boundary.rect.min_lon: 6
    #    boundary.rect.min_lat: 51
    #    boundary.rect.max_lon: 12
    #    boundary.rect.max_lat: 54
    #    boundary.country: DE
    #    layers: address
    #    size: 5
    #search_params: 
    #    boundary.rect.min_lon: 6
    #    boundary.rect.min_lat: 51
    #    boundary.rect.max_lon: 12
    #    boundary.rect.max_lat: 54
    #    boundary.country: DE
    #    layers: address
    #    size: 5
```

== Reference

=== storage
`type`: "sqlite"

Currently only SQLite can be used as database.

`database`: string

Path to SQLite file.

=== geocoder
`api`: string

"ors" | "bkg"

Geocoder API to use for address search.

"ors": Openrouteservice +
"bkg": BKG Geocoder

`api_key`: string

Key / token to access the geocoder API.

`suggest_params`: associative array

URL parameters for the suggest request to the geocoder can be added as scalars. The name of an attribute must correspond with an URL parameter or the geocoder API.

`search_params`: associative array

URL parameters for the search request to the geocoder can be added as scalars. The name of an attribute must correspond with an URL parameter or the geocoder API.

= Environment variables

The configuration parameters _api_ and _api_key_ from the configuration section _geocoder_ can be overridden by the following environment variables:

`VTMS_SEARCH_API`: string

"ors" | "bkg"

Geocoder API to use for address search.

"ors": Openrouteservice +
"bkg": BKG Geocoder

`VTMS_SEARCH_API_KEY`: string

Key / token to access the geocoder API.
